- hosts: all
  tasks:
  - name: perform update
    apt:
      update_cache: true
  - name: Install cowsay
    apt:
      name: cowsay
      state: present
  - name: Install lolcat
    apt:
      name: lolcat
      state: present
